# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'

# Build stage and deploy stage
stages:
  - stage: Build
    displayName: Build Image
    jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: 'ubuntu-latest'
      steps:

      # Docker compose file will build images
      - task: DockerCompose@0
        displayName: Build images
        inputs:
          containerregistrytype: 'Azure Container Registry'
          azureSubscription: 'azure-service-connection'
          azureContainerRegistry: '{"loginServer":"studentapplicationimages.azurecr.io", "id" : "/subscriptions/f488342a-bcf3-4095-9abd-4f737e0c9459/resourceGroups/kubernetes_dev/providers/Microsoft.ContainerRegistry/registries/StudentApplicationImages"}'
          dockerComposeFile: '$(Build.SourcesDirectory)/docker-compose.yml'
          action: 'Build services'
          additionalImageTags: '$(Build.BuildId)'
          includeLatestTag: true

      # Push images to Azure container Registry
      - task: DockerCompose@0
        displayName: Push images to azure container registry 
        inputs:          
          containerregistrytype: 'Azure Container Registry'
          azureSubscription: 'azure-service-connection'
          azureContainerRegistry: '{"loginServer":"studentapplicationimages.azurecr.io", "id" : "/subscriptions/f488342a-bcf3-4095-9abd-4f737e0c9459/resourceGroups/kubernetes_dev/providers/Microsoft.ContainerRegistry/registries/StudentApplicationImages"}'
          dockerComposeFile: '$(Build.SourcesDirectory)/docker-compose.yml'
          action: 'Push services'
          additionalImageTags: '$(Build.BuildId)'
          includeLatestTag: true

      # Copy yaml files for kubernetes to Artifacts Staging Directory
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)/DeploymentK8s'
          Contents: '**/*.yml'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      # Publish the files to Artifacts Staging Directory
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'manifests'
          publishLocation: 'Container'      
      
  # Deploy stage - Deploy to Kubernetes
  - stage: Deploy
    displayName: Deploy to Kubernetes
    jobs:
    - job: Deploy
      displayName: Deploy
      pool:
        vmImage: 'ubuntu-latest'
      steps:

      # Download build artifacts which are 2 yaml files - deployment.yml and mssql-deployment.yml for kubernetes
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'manifests'
          itemPattern: '**/*.yml'
          downloadPath: '$(System.ArtifactsDirectory)'

      # Deploy sql server image container to kubernetes
      - task: Kubernetes@1
        displayName: Deploy sql server image 
        inputs:
          connectionType: 'Azure Resource Manager'
          azureSubscriptionEndpoint: 'azure-service-connection'
          azureResourceGroup: 'kubernetes_dev'
          kubernetesCluster: 'eks_dev'
          command: 'apply'
          useConfigurationFile: true
          configuration: '$(System.ArtifactsDirectory)/manifests/mssql-deployment.yml'
          secretType: 'dockerRegistry'
          containerRegistryType: 'Azure Container Registry'
          azureSubscriptionEndpointForSecrets: 'azure-service-connection'
          azureContainerRegistry: 'studentapplicationimages.azurecr.io'
      
      # Deploy .net microservice student registration api image container to kubernetes
      - task: Kubernetes@1               
        displayName: Deploy student registration api
        inputs:
          connectionType: 'Azure Resource Manager'
          azureSubscriptionEndpoint: 'azure-service-connection'
          azureResourceGroup: 'kubernetes_dev'
          kubernetesCluster: 'eks_dev'
          command: 'apply'
          useConfigurationFile: true
          configuration: '$(System.ArtifactsDirectory)/manifests/deployment.yml'
          secretType: 'dockerRegistry'
          containerRegistryType: 'Azure Container Registry'
          azureSubscriptionEndpointForSecrets: 'azure-service-connection'
          azureContainerRegistry: 'studentapplicationimages.azurecr.io'
      
      
