apiVersion: apps/v1
kind: Deployment
metadata: 
  name: student-registration-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microsevice-pod
  template:
    metadata:
      labels:
        app: microsevice-pod
    spec:      
      containers:
      - name: student-registration-container
        image: leogether/studentregistration:v1
        ports:
        - containerPort: 80           
        env:
        - name: DBServer
          value: mssql-service
---        
apiVersion: v1
kind: Service
metadata:
  name: student-registration-service
spec:
  selector:
    app: microsevice-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30001
  type: LoadBalancer