apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mssql-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mssql-pod
  template:
    metadata:
      labels:
        app: mssql-pod
    spec:
      terminationGracePeriodSeconds: 30      
      containers:
      - name: mssql-container
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          value: "P@ssword1"
        - name: ACCEPT_EULA
          value: "Y"    
        - name: MSSQL_PID
          value: Express 
---        
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
spec:
  selector:
    app: mssql-pod
  ports:
    - name: sqlserver
      port: 1433
      targetPort: 1433
      
  type: ClusterIP